services:
  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: mosquitto_broker
    ports:
      - "1884:1883"
      - "8884:8883"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped